- README.md
- build.gradle
- src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
> bump up version to 1.0.3

- README.md
Added more Watson API test cases..
> Mock API test cases

- .travis.yml
- build.gradle
- pom.xml
- src/main/java/com/ibm/watson/developer_cloud/dialog/v1/DialogService.java
- src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/TrainingData.java
- src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/TrainingDataUtils.java
- src/test/resources/pizza_sample.xml
@germanattanasio	update dialog service to use the beta url and added dialog file #38	 9192687
@germanattanasio	Added apache.commons.lang to the wrappers and remove google collections …	 3aee042
@germanattanasio	add idks to travis and a dependency to grandle	 00bee5a
@germanattanasio	remove openjdk and only test against jdk7 and jdk8	 c0eeb8b
@germanattanasio	fix travis by adding lang3 to grande	 f1a050b
@germanattanasio	remove javadoc from grandle since it fails with jdk8	 34aab0a
Unified Split
> Fix travis and added lang3 and csv apache commons libraries 

- src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
- src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
- src/test/java/com/ibm/watson/developer_cloud/visual_insights/v1/VisualInsightsTest.java
Added unit tests for IllegalArgumentException to TTS, STT and VI
> Added unit tests for IllegalArgumentException

- .gitignore
- config.properties.example
Actually added before #89, but sufficient to be in a separate commit.
> Adds a sample config.properties

- src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/model/CombinedResults.java
Makes use of **Keywords** class
> CombinedResults fixes

- examples/retrieve-and-rank-solrj/src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/RetrieveAndRankSolrJExample.java
This prevents requests from being repeated when attempting
to authenticate through DataPower which causes SolrJ to fail.
> Use preemptive Basic auth when making request with SolrJ

- examples/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionCustomConfigExample.java
- src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversion.java
- src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java
- src/test/resources/document_conversion/answer_unit_config_selector_h2.json
The following commits include updates to the Document Conversion Service (added helper method in the service)
> Updates to DCS

- src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRank.java
- src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankIT.java
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
> Add R&R method to rank based on an InputStream

- src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/Voice.java
*  `ja-JP_EmiVoice`
*  `pt-BR_IsabelaVoice`
Related to #275
> Text to Speech voices

- README.md
- build.gradle
- examples/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/ConversationExample.java
- examples/java/com/ibm/watson/developer_cloud/dialog/v1/DialogServiceExample.java
- pom.xml
- src/main/java/com/ibm/watson/developer_cloud/http/ServiceCall.java
- src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
The purpose of this PR is making an initial reactive method in service call which is mentioned in #255 . 
I don't use the origin version which use Completable.supplyAsync to implement, as i think it will use ForkJoinPool. I think Okhttp client should already has a executor in enqueue method.
> [#255]Init reactive method for service call

- src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
- src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
As discussed with @germanattanasio, I migrated tests to OkHttp's MockWebServer and did some general refactoring.
> Improve Text-To-Speech and Speech-To-Text tests

- src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
- src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java
Per an internal discussion, change the User-Agent to be in the valid format for a User-Agent.
> Use a proper format for the User-Agent

- src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
- src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechIT.java
- src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
- src/test/resources/config.properties
add getVoice(String voiceName) function
> [text-speech] add getVoice() #287

- src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/util/ColumnTypeAdapter.java
- src/test/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalyticsIT.java
I added an example of how to use the sdk for Tradeoff Analytics with a caegorical column.
according to the DW question https://developer.ibm.com/answers/questions/275792/how-to-use-categoricalcolumn-is-there-any-example.html
> add example of categorical column

- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/KeywordsResult.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Transcript.java
- src/main/java/com/ibm/watson/developer_cloud/util/RequestUtils.java
- src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
Implemented the keyword spotting feature in the Speech-to-Text API
Fixes #299
> Add Speech-to-Text keyword spotting feature

- src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/Voice.java
- src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
Fixed Birgit naming (#304) 
Added Voice.getByName() lookup (#305)
> [text-to-speech] Improve Voice handling

- src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslation.java
- src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationIT.java
- src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationTest.java
Added methods to translate a List of Strings in `LanguageTranslation` (see #301) and migrated the unit tests to OkHttps `MockWebServer`.
> [language-translation] Support batch translation

- src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyDataNews.java
- src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyLanguage.java
- src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyVision.java
- src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/ConceptInsights.java
- src/main/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/ConversationService.java
- src/main/java/com/ibm/watson/developer_cloud/dialog/v1/DialogService.java
- src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversion.java
- src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslation.java
- src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifier.java
- src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsights.java
- src/main/java/com/ibm/watson/developer_cloud/relationship_extraction/v1_beta/RelationshipExtraction.java
- src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRank.java
- src/main/java/com/ibm/watson/developer_cloud/service/AlchemyService.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
- src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
- src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzer.java
- src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3_beta/ToneAnalyzer.java
- src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalytics.java
- src/main/java/com/ibm/watson/developer_cloud/visual_insights/v1_experimental/VisualInsights.java
- src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v2_beta/VisualRecognition.java
- src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java
add constructor method with username and password. #298
> add constructor method with username and password. #298

- src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/model/ContentItem.java
- src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsIT.java
- src/test/resources/personality_insights/contentItems.json
> [personality-insights] Added custom type adapter to ContentItem #307

- src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsIT.java
> Fix PersonalityInsightsIT file spelling

- src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierIT.java
- src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankIT.java
This should increase test stability (see #324)
> Replace flaky assertions with assumptions

- pom.xml
- src/test/java/com/ibm/watson/developer_cloud/WatsonServiceTest.java
- src/test/java/com/ibm/watson/developer_cloud/WatsonServiceUnitTest.java
- src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java
- src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
- src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
- src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3_beta/ToneAnalyzerTest.java
Migrated remaining unit tests and removed dependency 
See #316
> Remove MockServer test dependency

- src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyDataNews.java
- src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyLanguage.java
Fixes a problem with `AlchemyLanguage` and `AlchemyDataNews`: Their methods changed a `Map` that the user supplied, causing mutability problems.
> Fix Map mutability issue

- src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/model/AcceptLanguage.java
> Add Arabic and Japanese support for Personality Insights

- src/main/java/com/ibm/watson/developer_cloud/http/NameValue.java
- src/main/java/com/ibm/watson/developer_cloud/http/RequestBuilder.java
- src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/util/SpeechTimestampTypeAdapter.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/util/SpeechWordConfidenceTypeAdapter.java
- src/main/java/com/ibm/watson/developer_cloud/util/DateDeserializer.java
- src/main/java/com/ibm/watson/developer_cloud/util/DateSerializer.java
- src/main/java/com/ibm/watson/developer_cloud/util/LongToDateTypeAdapter.java
- src/main/java/com/ibm/watson/developer_cloud/util/RequestUtils.java
- src/main/java/com/ibm/watson/developer_cloud/util/Validator.java
- src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java
- src/test/java/com/ibm/watson/developer_cloud/http/NameValueTest.java
- src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java
- src/test/java/com/ibm/watson/developer_cloud/service/RequestBuilderTest.java
- src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerTest.java
- src/test/java/com/ibm/watson/developer_cloud/util/TypeAdaptersTest.java
Improved `NameValue`, `RequestBuilder`, `RequestUtils` and `VisualRecognition`
> Refactor general sdk code and expand tests

- src/main/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/model/MessageResponse.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognizeOptions.java
This fixes a `NullPointerException` that may occur during several `clone()` invocations.
> Fix array clone NullPointerException

- src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/model/ContentItem.java
- src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsIT.java
- src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsTest.java
> Fix issue 339

- src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java
Added a unit test for utility class constructors
> Add unit test for utility class constructors

- src/main/java/com/ibm/watson/developer_cloud/util/DateDeserializer.java
- src/main/java/com/ibm/watson/developer_cloud/util/DateSerializer.java
Improved the null handling of Date serialization and deserialization (especially converting empty JSON String literals `""` to `null`)
> Improve null handling of Date(De)Serializer

- src/main/java/com/ibm/watson/developer_cloud/service/exception/ServiceResponseException.java
> Fix ServiceResponseException null pointer

- examples/retrieve-and-rank-solrj/pom.xml
- examples/retrieve-and-rank-solrj/src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/RetrieveAndRankSolrJExample.java
Use version 5.5.1 of SolrJ
Execute calls to the config API synchronously
> Update R&R SolrJ example

- examples/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationExample.java
regarding TextToSpeech, we have supported custom voice model.
So add the example about this.
> [text-to-speech] add customization example

- examples/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationExample.java
add the example about speech synthesize with custom voice model.
> [TextToSpeech] add speech synthesize with custom voice model.

- src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/util/ConversionUtils.java
- src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/model/TranslationResult.java
- src/main/java/com/ibm/watson/developer_cloud/service/AlchemyService.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/util/MediaTypeUtils.java
- src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/model/column/Column.java
- src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java
- src/main/java/com/ibm/watson/developer_cloud/util/RequestUtils.java
- Refactored MediaTypes
- Improved null documentation
- Improved some Exception handling
> Refactoring

- examples/java/com/ibm/watson/developer_cloud/speech_to_text/v1/MicrophoneWithWebSocketsExample.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/BaseRecognizeCallback.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/WebSocketManager.java
> Implement continuous speech-to-text recognition

- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechModel.java
- src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
Addresses #393.  Adds description to the model for TTS
> Adds description from speech model for TTS

- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechWordAlternative.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Transcript.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/WordAlternative.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/WordAlternativeTypeAdapter.java
In order to get "word_alternatives" from the results in the module of "speech to text", add code "private List wordAlternatives;" in Transcript.java. then add the SpeechWordAlternative.java and WordAlternative.java for accept json String of result. Also, the "WordAlternativeTypeAdapter.java" is for parsing json object
Something wrong with merge request "Word alternatives #390", so i closed the merger request. This is the new merge request.
> Word alternatives

- src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ClassifyImagesOptions.java
- src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionTest.java
Fix a null pointer exception in the visual recognition example.
> :bug: fix visual recognition example

- src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslation.java
Doc comments refer to old name of the class. Fixes #410
> fixes misstatement in doc comment

- src/main/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationService.java
- src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/MessageRequest.java
- src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/model/Answers.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
- src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognizeOptions.java
- src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationServiceIT.java
- src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationTest.java
This PR fixes some issues reported by @Mikemosca
> Conversation

- src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRank.java
- src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/SolrClusterOptions.java
- src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/SolrClusterResizeRequest.java
- src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java
- src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankTest.java
This PR enables tests that were failing
> Retrieve and Rank unit tests

- retrieve-and-rank/src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRank.java
> Add topAnswers for R&R when ranking on InputStreams as well

- discovery/README.md
- examples/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryQueryExample.java
Adds in readme example + a real end-to-end example for discovery
> Update readme for discovery and add example

- natural-language-classifier/README.md
new url for docs after conversion to Markdown
> Update link to NLC docs

- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceTest.java
- discovery/src/test/resources/discovery/create_coll_resp.json
- discovery/src/test/resources/discovery/create_conf_resp.json
- discovery/src/test/resources/discovery/create_doc_resp.json
- discovery/src/test/resources/discovery/create_env_resp.json
- discovery/src/test/resources/discovery/delete_coll_resp.json
- discovery/src/test/resources/discovery/delete_conf_resp.json
- discovery/src/test/resources/discovery/delete_doc_resp.json
- discovery/src/test/resources/discovery/delete_env_resp.json
- discovery/src/test/resources/discovery/get_coll1_resp.json
- discovery/src/test/resources/discovery/get_coll_resp.json
- discovery/src/test/resources/discovery/get_conf_resp.json
- discovery/src/test/resources/discovery/get_confs_resp.json
- discovery/src/test/resources/discovery/get_doc_resp.json
- discovery/src/test/resources/discovery/get_env_resp.json
- discovery/src/test/resources/discovery/get_envs_resp.json
- discovery/src/test/resources/discovery/listfields_coll_resp.json
- discovery/src/test/resources/discovery/query1_resp.json
- discovery/src/test/resources/discovery/update_conf_resp.json
- discovery/src/test/resources/discovery/update_doc_resp.json
- discovery/src/test/resources/discovery/update_env_resp.json
Add Discovery unit tests and fixture son files for each class
> Add Discovery unit tests

- tone-analyzer/README.md
for https://github.ibm.com/Watson/developer-experience/issues/1796
Updating the Tone doc link so that it doesn't redirect
> updating Tone doc link so it doesn't redirect 

- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/WebSocketManager.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/AudioFormat.java
Fixes #550 removes warning on build
Fixes #548 Fixes typo in method name.
> Fixes a couple of issues.

- visual-recognition/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionTest.java
- visual-recognition/src/test/resources/visual_recognition/collection.json
- visual-recognition/src/test/resources/visual_recognition/image.json
new unit tests for similarity search
> new unit tests for similarity search

- .travis.yml
- language-translation/src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationIT.java
- language-translator/src/test/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslatorIT.java
- retrieve-and-rank/src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankIT.java
- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
- speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/AddImageToCollectionOptions.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ClassifierOptions.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ClassifyImagesOptions.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/Collection.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/CollectionImage.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/Face.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/FindSimilarImagesOptions.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ImageProcessed.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ImageProcessingError.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ImageProcessingWarning.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ImageText.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/Location.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/VisualClassifier.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/VisualRecognitionGenericModel.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/VisualRecognitionOptions.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/Word.java
- visual-recognition/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionIT.java
Some integration tests were not calling `.execute()` so this PR includes that and Similarity Search
Most of the changes are because I re-sort the methods in the visual recognition package.
Fixes #508
> Add Similarity search support

- README.md
- alchemy/build.gradle
- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java
- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceTest.java
- natural-language-classifier/src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierIT.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java
- visual-recognition/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionIT.java
- visual-recognition/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionTest.java
> fix the gradle check errors

- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationService.java
- conversation/src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationTest.java
- examples/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationExample.java
Update the Conversation API wrapper classes to include the 2017-02-03 API version
> :new:update the conversation API wrapper to refer to the latest version

- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
- speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
- speech-to-text/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
While playing around with the library I wrote a test to verify some behaviour. Might be useful for you because it demonstrates how to test the speech-to-text component with MockWebServer. I also changed the URL rewriting because rewriting everything to wss (and by that requiring the use of TLS) makes it impossible to test with MockWebServer.
> Enhance test coverage of speech-to-text

- conversation/src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationTest.java
Version was changed in f73d9490cf5f637c9a99a1c707fa455458bd27a4 but assertions not updated. Breaks the build, at least locally.
> Fix incorrect assertions

- alchemy/src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyLanguageIT.java
- speech-to-text/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
- visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java
Small updates to address JavaDoc issues.
> Address other small JavaDoc issues across build

- CHANGELOG.md
Documented visible functional updates to the Speech to Text and Text to Speech services.
> :memo: Update CHANGELOG.md file

- CHANGELOG.md
Add the Tradeoff Analytics updates to the CHANGELOG for the next release.
> :memo: Update CHANGELOG.md for new Tradeoff Analytics features

- README.md
- build.gradle
1) Add code coverage to gradle
2) Add the ability to aggregate all the test results in each sub
project to 1 report
> add code coverage to gradle

- alchemy/build.gradle
- conversation/build.gradle
- core/build.gradle
- dialog/build.gradle
- discovery/build.gradle
- document-conversion/build.gradle
- gradle.properties
- java-sdk/build.gradle
- language-translation/build.gradle
- language-translator/build.gradle
- natural-language-classifier/build.gradle
- personality-insights/build.gradle
- retrieve-and-rank/build.gradle
- speech-to-text/build.gradle
- text-to-speech/build.gradle
- tone-analyzer/build.gradle
- tradeoff-analytics/build.gradle
- visual-recognition/build.gradle
PR for for publishing the sdk jars to maven central
> metadata, pom signing and catch-all java-sdk module

- RELEASE.md
Just updating release instructions
> Updating RELEASE with gradle instructions

- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
- text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
Text is now encoded in `synthesize`
Resolves #602
> TTS encoding 

- natural-language-understanding/README.md
Fixes #634.  Adds a README.md for Natural Language Understanding.
> [NLU] Add README.md

- natural-language-understanding/README.md
Current example uses an invalid constructor, version date is required
> Fix NLU example

- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/WebSocketManager.java
Reverts watson-developer-cloud/java-sdk#657
> Revert "STT: Close websocket after all data processed"

- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationService.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CounterexampleCollectionResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CreateDialogNode.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CreateEntity.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CreateExample.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CreateIntent.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CreateValue.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/CreateWorkspace.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/EntityExportResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/EntityResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/ExampleCollectionResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/ExampleResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/IntentCollectionResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/IntentExportResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/IntentResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/PaginationResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/UpdateWorkspace.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/ValueExportResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/ValueResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/WorkspaceCollectionResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/WorkspaceExportResponse.java
- conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/model/WorkspaceResponse.java
- conversation/src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationServiceIT.java
> Add support for workspace, intent, example, and counterexample APIs

- language-translation/src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslation.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationModel.java
- language-translator/src/test/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslatorIT.java
- visual-recognition/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionIT.java
> Adds serializedName for TranslatorModel

- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java
Improves reliability of Discovery integration tests run in local test environment.
> Improve reliability of Discovery integration tests

- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/BaseRecognizeCallback.java
- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/RecognizeCallback.java
- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/SpeechToTextWebSocketListener.java
- speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
- speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
> Adds a method to the STT websocket callback

- android-utils/library/src/main/java/com/ibm/watson/developer_cloud/android/library/audio/opus/OggOpusEnc.java
Comments out a line of code that will endlessly spew to your log on android.
Nothing more important.
> Comments out debug code

- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Word.java
- speech-to-text/src/test/java/okhttp3/internal/ws/WebSocketRecorder.java
Very minor checkstyle violations, but they were making trouble for
me so I fixed them.  Fixes #712.
> Fixes checkstyle violations

- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java
Add test for issue #659.  The test passes so the issue is closed as invalid.
> Test for problem reported in issue 659

- build.gradle
- core/src/main/java/com/ibm/watson/developer_cloud/http/HttpClientSingleton.java
- core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
* Fixes  [speech-to-text] Recent commit removed ability to configure OkHttpClient for services #722
* Fixes #705 Adds gradle idea plugin
> Fix various issues

- retrieve-and-rank/build.gradle
> Recover testCompile dependency to fix test build

- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
Calling configureHttpClient method to enable overriding
> Call configureHttpClient to enable overriding

- README.md
- core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
Added troubleshooting section, fixed bug in setEndPoint(). #748
> setEndpoint info and bugfix

- discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
- discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/CreateTrainingExampleOptions.java
- discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/TrainingExample.java
- discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/UpdateTrainingExampleOptions.java
- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java
- discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceTest.java
- discovery/src/test/resources/discovery/add_training_example_resp.json
- discovery/src/test/resources/discovery/add_training_query_resp.json
- discovery/src/test/resources/discovery/get_training_data_resp.json
- discovery/src/test/resources/discovery/get_training_example_resp.json
- discovery/src/test/resources/discovery/list_training_data_resp.json
- discovery/src/test/resources/discovery/update_training_example_resp.json
The new Training Data endpoint is tested. Some models were also changed
to make tests pass, as they were generated wrong. This issue has since
been fixed.
> Add unit and integration tests

- conversation/src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationServiceIT.java
- conversation/src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationTest.java
Passing unit and integration tests have been added for the new DialogNode methods.
> Add DialogNode tests

- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/CreateModelOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/ListModelsOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslateOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationModel.java
This PR contains the newest generated code to be put in the SDK 4.0 release.
> Add newest generated code

- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Behavior.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ConsumptionPreferences.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ContentItem.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Profile.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ProfileOptions.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Trait.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Warning.java
This PR contains the newest generated code to be put in the SDK 4.0 release.
> Update generated SDK for PersonalityInsights

- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzer.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/DocumentAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/SentenceAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneChatOptions.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneChatScore.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneInput.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneOptions.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneScore.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/Utterance.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/UtteranceAnalyses.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/UtteranceAnalysis.java
Used `watson-swagger-codegen` to generate java files for latest version of Tone. Adds support for French, new API response for version parameter `2017-09-21`
> Added Generated SDK files for new version of Tone

- natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/DocumentSentimentResults.java
- natural-language-understanding/src/test/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstandingTest.java
Copy of PR #815 to keep `develop` in sync
> Document sentiment result label dev

- .utility/generate_index_html.sh
- alchemy/src/test/resources/alchemy/example.html
- discovery/README.md
- language-translator/README.md
- natural-language-classifier/README.md
- natural-language-understanding/README.md
- speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/KeywordsResult.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/CustomTranslation.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/CustomVoiceModel.java
- visual-recognition/README.md
Updating links that point to WDC documentation to go to the Watson console. 
Also updating or removing other links that are outdated.
This branch was created off master. So perhaps this PR should be closed. Created PR #845 for master.
> Update links to developercloud

- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzer.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/DocumentAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/SentenceAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneCategory.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneChatOptions.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneChatScore.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneInput.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneOptions.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneScore.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/Utterance.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/UtteranceAnalyses.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/UtteranceAnalysis.java
- tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/package-info.java
- tone-analyzer/src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerIT.java
- tone-analyzer/src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerTest.java
This PR adds new newest generated code for Tone Analyzer as of 2/8/18 for the purpose of the Java SDK 5.0.0 release.
> Add newest generated code for Tone Analyzer

- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Behavior.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ConsumptionPreferences.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ConsumptionPreferencesCategory.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Content.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ContentItem.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Profile.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ProfileOptions.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Trait.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Warning.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/package-info.java
- personality-insights/src/test/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsightsIT.java
- personality-insights/src/test/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsightsTest.java
This PR adds new newest generated code for Personality Insights as of 2/8/18 for the purpose of the Java SDK 5.0.0 release.
> Add newest generated code for Personality Insights

- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/CreateModelOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/DeleteModelOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/GetModelOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiableLanguage.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiableLanguages.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiedLanguage.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiedLanguages.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/ListModelsOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslateOptions.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/Translation.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationModel.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationModels.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationResult.java
- language-translator/src/test/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslatorTest.java
- language-translator/src/test/resources/language_translation/identify_response.json
- language-translator/src/test/resources/language_translation/multiple_translations.json
- language-translator/src/test/resources/language_translation/single_translation.json
This PR adds the newest Language Translator code as of the week of 03/05/18.
> [Language Translator] Add newest generated code and update tests

- README.md
- conversation/README.md
- discovery/README.md
- natural-language-understanding/README.md
- tone-analyzer/README.md
- visual-recognition/README.md
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
> docs(versions): Update references to old static version strings

- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/Assistant.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/CreateDialogNode.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/DialogNode.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/DialogNodeVisitedDetails.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListAllLogsOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListCounterexamplesOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListDialogNodesOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListEntitiesOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListExamplesOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListIntentsOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListLogsOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListSynonymsOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListValuesOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/ListWorkspacesOptions.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/MessageRequest.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/model/MessageResponse.java
- assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/package-info.java
- assistant/src/test/java/com/ibm/watson/developer_cloud/assistant/v1/AssistantTest.java
- assistant/src/test/resources/assistant/assistant.json
This PR adds the latest changes in the Assistant service as of 4/17/18.
> [Assistant] Add newest generated code

- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslateOptions.java
This PR adds the latest changes in the Language Translator service as of 4/17/18.
> [Language Translator] Add newest generated code

- natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java
This PR adds the latest changes in the Natural Language Understanding service as of 4/17/18.
> [Natural Language Understanding] Add newest generated code

- natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Behavior.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ConsumptionPreferences.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ConsumptionPreferencesCategory.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ContentItem.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Profile.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ProfileOptions.java
- personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/Trait.java
This PR adds the latest changes in the Personality Insights service as of 4/17/18.
> [Personality Insights] Add newest generated code

- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/AddWordOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/AddWordsOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/DeleteVoiceModelOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/DeleteWordOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/GetPronunciationOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/GetVoiceModelOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/GetVoiceOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/GetWordOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/ListWordsOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/SynthesizeOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/UpdateVoiceModelOptions.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/VoiceModel.java
- text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/Words.java
This PR adds the latest changes in the Text to Speech service as of 4/17/18.
> [Text to Speech] Add newest generated code

- README.md
Update README to support changes to Visual Recognition after May 22
- Add section. We can remove the set URL info with the next version of the SDK. We can remove the whole section when the old API Key auth is no longer supported
- Update info about Visual Recognition and api keys
> Update info about Visual Recognition

- README.md
TTL of the token is already mention in the para above
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
> Fix extra mention of token validity

- README.md
This pull request adds a `Before You Begin` section and a java sdk specific tracking link for IBM Cloud onboarding.
> Add tracking link

- README.md
- language-translator/README.md
- language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java
This PR adds doc changes for authentication and Language Translator v2 deprecation, as well as an onboarding link.
> Release v6.1.1

- core/src/main/java/com/ibm/watson/developer_cloud/util/ResponseConverterUtils.java
- core/src/main/java/com/ibm/watson/developer_cloud/util/ResponseUtils.java
This PR adds support for non-object response values like bare integers and strings.
> Core changes for bare integer responses

- core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
- core/src/test/java/com/ibm/watson/developer_cloud/service/AuthenticationTest.java
Fix bugs when different authentication of each instance of same service if there is vcapserices environment.
This bug happend my cloudfoundry app when bind two discovery servicies.
I need this patch until complete of migration authentication from old to iam.
> Fix credencials patch

- .github/ISSUE_TEMPLATE/bug_report.md
- .utility/generate_apidiff_index_html.sh
- .utility/generate_index_html.sh
- README.md
- assistant/README.md
- assistant/src/main/java/com/ibm/watson/assistant/v2/model/CreateSessionOptions.java
- assistant/src/main/java/com/ibm/watson/assistant/v2/model/DeleteSessionOptions.java
- assistant/src/main/java/com/ibm/watson/assistant/v2/model/MessageOptions.java
- discovery/README.md
- examples/src/main/java/com/ibm/watson/assistant/v1/tone_analyzer_integration/ToneDetection.java
- language-translator/README.md
- natural-language-classifier/README.md
- natural-language-understanding/README.md
- natural-language-understanding/src/main/java/com/ibm/watson/natural_language_understanding/v1/model/AnalyzeOptions.java
- personality-insights/README.md
- speech-to-text/README.md
- speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/CreateSessionOptions.java
- speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/MultipartRecognition.java
- text-to-speech/README.md
- text-to-speech/src/main/java/com/ibm/watson/text_to_speech/v1/model/CustomWord.java
- tone-analyzer/README.md
- visual-recognition/README.md
This pull request refactors bluemix to cloud.ibm with the exception of links to bluemix apps.
> Refactor bluemix to cloud.ibm

- natural-language-understanding/README.md
typo in the README for NLU
one character typo
> typo in .getResult

- .travis.yml
- .utility/decrypt-service-instance-apikeys.sh
- .utility/deploy-travis-wrapper.sh
- .utility/patch-openjdk7.sh
- .utility/push-javadoc-to-gh-pages.sh
- .utility/travis-run-tests.sh
- assistant/src/test/java/com/ibm/watson/assistant/v1/AssistantServiceIT.java
- build.gradle
- discovery/src/test/java/com/ibm/watson/discovery/v1/DiscoveryServiceIT.java
- gradle.properties
Switch to use travis stages in order to prevent integration tests from failing the build
> build: switch to travis stages

- assistant/src/main/java/com/ibm/watson/assistant/v1/model/DialogNodeOutputGeneric.java
- compare-comply/README.md
This pull request updates outdated links in documentation. Current redirects for these links will stop in May. This change has been made in the API definition.
> Update outdated links

- README.md
add transaction id documentation
> docs(readme): add transaction id documentation

- visual-recognition/src/main/java/com/ibm/watson/visual_recognition/v4/VisualRecognition.java
- visual-recognition/src/main/java/com/ibm/watson/visual_recognition/v4/model/CreateCollectionOptions.java
- visual-recognition/src/main/java/com/ibm/watson/visual_recognition/v4/model/UpdateCollectionOptions.java
- visual-recognition/src/test/java/com/ibm/watson/visual_recognition/v4/VisualRecognitionTest.java
- visual-recognition/src/test/java/com/ibm/watson/visual_recognition/v4/model/CreateCollectionOptionsTest.java
- visual-recognition/src/test/java/com/ibm/watson/visual_recognition/v4/model/UpdateCollectionOptionsTest.java
We should **not** have trainingStatus as a parameter for VisRec V4 CreateCollection and UpdateCollection operations. This field is marked as readonly
> Update visual rec

- .github/workflows/build-test.yml
Add build and test via github actions
[skip ci] dont run travis on this
> ci: 9258 gha

- .github/workflows/deploy.yml
- README.md
- build/publish_gha.sh
- build/setMavenVersion.sh
- build/setMavenVersion_gha.sh
Add the deploy part using GHA and turn off travis.
> ci: Add deploy via GHA

- .github/workflows/deploy.yml
- build/publish_gha.sh
> ci: Gha 9747

- .github/workflows/deploy.yml
- build/publish_gha.sh
Fix java docs upload [skip ci]
> ci: Gha 9758 [skip ci]

- .github/workflows/integration-test.yml
- assistant/src/test/java/com/ibm/watson/assistant/v1/AssistantServiceIT.java
- assistant/src/test/java/com/ibm/watson/assistant/v1/AssistantServiceTest.java
- assistant/src/test/java/com/ibm/watson/assistant/v2/AssistantServiceTest.java
- compare-comply/src/test/java/com/ibm/watson/compare_comply/v1/CompareComplyServiceIT.java
- compare-comply/src/test/java/com/ibm/watson/compare_comply/v1/CompareComplyServiceTest.java
- discovery/src/test/java/com/ibm/watson/discovery/v1/DiscoveryServiceIT.java
- discovery/src/test/java/com/ibm/watson/discovery/v2/DiscoveryIT.java
- language-translator/src/test/java/com/ibm/watson/language_translator/v3/LanguageTranslatorIT.java
- natural-language-classifier/src/test/java/com/ibm/watson/natural_language_classifier/v1/NaturalLanguageClassifierIT.java
- natural-language-understanding/src/test/java/com/ibm/watson/natural_language_understanding/v1/NaturalLanguageUnderstandingIT.java
- personality-insights/src/test/java/com/ibm/watson/personality_insights/v3/PersonalityInsightsIT.java
- pom.xml
- speech-to-text/src/test/java/com/ibm/watson/speech_to_text/v1/SpeechToTextIT.java
- text-to-speech/src/test/java/com/ibm/watson/text_to_speech/v1/CustomizationsIT.java
- text-to-speech/src/test/java/com/ibm/watson/text_to_speech/v1/TextToSpeechIT.java
- tone-analyzer/src/test/java/com/ibm/watson/tone_analyzer/v3/ToneAnalyzerIT.java
- visual-recognition/src/test/java/com/ibm/watson/visual_recognition/v3/VisualRecognitionIT.java
- visual-recognition/src/test/java/com/ibm/watson/visual_recognition/v4/VisualRecognitionIT.java
> ci: Gha 9907

- .bumpversion.cfg
> fix(bumpversion): update bumpversion file

- language-translator/src/main/java/com/ibm/watson/language_translator/v3/LanguageTranslator.java
- language-translator/src/main/java/com/ibm/watson/language_translator/v3/model/CreateModelOptions.java
- language-translator/src/test/java/com/ibm/watson/language_translator/v3/LanguageTranslatorTest.java
- language-translator/src/test/java/com/ibm/watson/language_translator/v3/model/CreateModelOptionsTest.java
Add content-type to properties that require a file within the createModelOptions class
>  fix(language-translator-v3): add content-type to createModelOptions model properties

- .github/workflows/deploy.yml
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
> build(actions): use node 18 in deploy.yml

- common/src/test/java/com/ibm/watson/common/WatsonServiceUnitTest.java
- language-translator/src/test/java/com/ibm/watson/language_translator/v3/LanguageTranslatorIT.java
- pom.xml
- text-to-speech/src/test/java/com/ibm/watson/text_to_speech/v1/CustomizationsIT.java
- text-to-speech/src/test/java/com/ibm/watson/text_to_speech/v1/CustomizationsTest.java
This upgrade is mainly to remove the vulnerable guava dependency
> fix(pom): upgrade sdk-core

- assistant/src/main/java/com/ibm/watson/assistant/v2/model/MessageOutputDebugTurnEvent.java
- assistant/src/main/java/com/ibm/watson/assistant/v2/model/MessageOutputDebugTurnEventTurnEventConversationalSearchEnd.java
- assistant/src/test/java/com/ibm/watson/assistant/v2/model/MessageOutputDebugTurnEventTurnEventConversationalSearchEndTest.java
This patch adds the conversational_search_end turn event type
> fix(wa-v2): add conversational_search_end turn event
