src/main/java/com/ibm/watson/developer_cloud/concept_expansion/v1/ConceptExpansion.java
src/main/java/com/ibm/watson/developer_cloud/concept_expansion/v1/model/Concept.java
src/main/java/com/ibm/watson/developer_cloud/language_identification/v1/LanguageIdentification.java
src/main/java/com/ibm/watson/developer_cloud/language_identification/v1/model/IdentifiedLanguage.java
src/main/java/com/ibm/watson/developer_cloud/machine_translation/v1/MachineTranslation.java
src/main/java/com/ibm/watson/developer_cloud/machine_translation/v1/model/Language.java
src/main/java/com/ibm/watson/developer_cloud/message_resonance/v1/MessageResonance.java
src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifier.java
src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/Classification.java
src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/ClassifiedClass.java
src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/Classifier.java
src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/TrainingData.java
src/main/java/com/ibm/watson/developer_cloud/package-info.java
src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsights.java
src/main/java/com/ibm/watson/developer_cloud/personality_insights/v2/model/Trait.java
src/main/java/com/ibm/watson/developer_cloud/question_and_answer/v1/QuestionAndAnswer.java
src/main/java/com/ibm/watson/developer_cloud/relationship_extraction/v1/RelationshipExtraction.java
src/main/java/com/ibm/watson/developer_cloud/service/Request.java
src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
src/main/java/com/ibm/watson/developer_cloud/service/package-info.java
src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
src/main/java/com/ibm/watson/developer_cloud/util/MediaType.java
src/main/java/com/ibm/watson/developer_cloud/util/RequestUtil.java
src/main/java/com/ibm/watson/developer_cloud/util/ResponseUtil.java
src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v1/VisualRecognition.java
src/test/java/com/ibm/watson/developer_cloud/WatsonServiceTest.java

Java 8 has stricter javadoc checking (it cannot have <pre> nested in <code>, no '<' and '>' characters in javadoc and some stricter checking on @param names)

Fixing javadoc for Java 8

---

.gitignore
src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/ConceptInsights.java
src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/model/Concept.java
src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/model/Corpus.java
src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/model/Document.java
src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/model/Graph.java
src/main/java/com/ibm/watson/developer_cloud/concept_insights/v2/util/IDHelper.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyVisionTest.java
src/test/java/com/ibm/watson/developer_cloud/concept_insights/v2/ConceptInsightsTest.java
src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationTest.java
src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierTest.java
src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
src/test/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalyticsTest.java
src/test/java/com/ibm/watson/developer_cloud/visual_insigths/v1/VisualInsightsTest.java

* Update CI models to allow users to specify the `accountId` and `corpusName`
* Renamed `IDValidator` to `IDHelper`
* Splitted `getRelatedConcept` into two methods that now require parameters
outside of the parameters map
* updated test cases

Update Concept Insights models and tests cases based on a code review with nizar

---

.gitignore
src/test/java/com/ibm/watson/developer_cloud/visual_insights/v1/VisualInsightsTest.java

Renamed dir path for Visual Insights as it had a typo.  Also fixed the package name in test class VisualInsightsTest.java to match new dir path

renaming Insigths to Insights(typo fix)

---

src/test/java/com/ibm/watson/developer_cloud/MultiThreadTest.java
src/test/java/com/ibm/watson/developer_cloud/WatsonServiceTest.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyDataNewsTest.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyLanguageTest.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyVisionTest.java
src/test/java/com/ibm/watson/developer_cloud/concept_expansion/v1/ConceptExpansionTest.java
src/test/java/com/ibm/watson/developer_cloud/concept_insights/v2/ConceptInsightsTest.java
src/test/java/com/ibm/watson/developer_cloud/dialog/v1/DialogServiceTest.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java
src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationTest.java
src/test/java/com/ibm/watson/developer_cloud/message_resonance/v1/MessageResonanceTest.java
src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierTest.java
src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsTest.java
src/test/java/com/ibm/watson/developer_cloud/question_and_answer/v1/QuestionAndAnswerTest.java
src/test/java/com/ibm/watson/developer_cloud/relationship_extraction/v1/RelationshipExtractionTest.java
src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java
src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v1/ToneAnalyzerTest.java
src/test/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalyticsTest.java
src/test/java/com/ibm/watson/developer_cloud/visual_insights/v1/VisualInsightsTest.java
src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v1/VisualRecognitionTest.java

Checks for nulls and empty strings in properties when retrieved, then throws a rather explicit exception when something is wrong.
Backstory:
I checked out the code to use the R&R branch, but didn't understand what was wrong when I ran tests and got a bunch of NPEs. I dug a little more and found that there's a developer-specific configuration file necessary. Put the file in place, but still couldn't figure out what goes into it. This was a result, as I could easily find all of the properties needed through this and through some grepping.
A sample config is forthcoming.

Handles missing testing properties safely

---

src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/model/Entity.java

@germanattanasio **Note** I'm not 100% sure how @link works, so I've made an educated guess, please correct me if I'm wrong :)
Otherwise
* Corrects service that Entities belongs to
* Inherits from correct class
* Shares credit with all of IBM

Entity fixes

---

src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/SolrCluster.java
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/SolrClusterOptions.java
src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankIntegrationTest.java

The Retrieve and Rank service uses a String tp represent a Solr cluster's
size in its JSON responses. As a result, our Gson objects have to also
use Strings otherwise serialization will fail.

Use Strings to parse Solr cluster size in Retrieve and Rank

---

src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversion.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java
src/test/resources/document_conversion/custom_config.json

Adds SDK support for passing custom configurations to the Document Conversion Service. Configuration is passed as a JsonObject in order to minimize SDK changes in the event of future configuration changes.

DCS: Adds support for using custom configs

---

src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversion.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java

The Document Conversion Service will soon require a "version" query
parameter on all requests. In the future, this will be used to avoid
breaking changes to behavior when the service is upgraded to newer
versions.

[DCS] Adds Version Date param

---

src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechAlternative.java
src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechTimestamp.java
src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechWordConfidence.java
src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/util/SpeechTimestampTypeAdapter.java
src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/util/SpeechWordConfidenceTypeAdapter.java
src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java

Added support for Timestamps and Word Confidences utilizing GSON Annotations and TypeAdapter as per @germanattanasio suggestion in PR #146 .
Still need to run Integration Testing.

[speech-to-text] Add support for Timestamp and Word Confidence

---

src/main/java/com/ibm/watson/developer_cloud/http/InputStreamRequestBody.java

It isn't good practice to use inputstream.available() as the content length. By default RequestBody has -1, which means content length is unknown. It is my understanding that this is common practice. So, I have removed the override contentLength() method. The RequestBody version will work.
Resolve issue #180

Resolve inputstream incorrect content length

---

.utility/push-javadoc-to-gh-pages.sh

This is to answer the docs team's request to be able to link to the latest release's javadoc without continually having to update things. It should also make life easier on us.
This actually points to the latest tag, so if you, say, release v3.0.0 and then go back and publish v2.9.1 with a bugfix, the latest/ link will change to v2.9.1 until you release a new v3.x. (Or you change it manually in the `gh-pages` branch.)
I'm sending this as a PR rather than committing it so that @germanattanasio can review it and choose when to test it on a new release.

automatically create latest/ symlink in docs for tagged builds

---

.gitignore
build.gradle

The purpose of this PR is making the idea IDE buid work and ignore idea files. You can review it, thanks.

[java-sdk] Fix idea build and ignore idea .ipr file

---

examples/java/com/ibm/watson/developer_cloud/alchemy_data_news/v1/GetNewsDocumentExample.java

added sample queries on various fields, including adjacent nested fields

added example query calls to examples/GetNewsDocumentExample.java

---

src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyLanguage.java
src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/model/LanguageSelection.java

This will allow users to select a language to use with AlchemyLanguage. They can also choose "DETECT", which is also the default.

Allow users to select language for AlchemyLanguage

---

src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/util/TaxonomyTypeAdapter.java

Fix to have TaxonomyTypeAdapter's write() method produce output that's also accepted by its read() method.
This bug resulted in an uncaught exception when trying to re-read a serialized POJO, e.g.:
```
java.lang.IllegalStateException: Expected a string but was BOOLEAN at line 5 column 24 path $.taxonomy[0].confident
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:831)
at com.ibm.watson.developer_cloud.alchemy.v1.util.TaxonomyTypeAdapter.read(TaxonomyTypeAdapter.java:49)
at com.ibm.watson.developer_cloud.alchemy.v1.util.TaxonomyTypeAdapter.read(TaxonomyTypeAdapter.java:27)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFa …
```

[alchemy] Bug fix for TaxonomyTypeAdapter serialization

---

src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/model/ImageKeyword.java
src/main/java/com/ibm/watson/developer_cloud/alchemy/v1/util/ImageKeywordTypeAdapter.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyVisionIT.java

Adds the `hierarchy` field and accessors to the `ImageKeyword` class so this data from the api can be exposed. See https://github.com/watson-developer-cloud/java-sdk/issues/235
Did not do a full test since I do not have values for the entire `config.properties` list. I ran only the modified test using `gradle test -Dtest.single=AlchemyVisionIT` and my alchemy api key and verified it passed.

add a hierarchy property and modify the adapter to read it #235

---

src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslation.java
src/main/java/com/ibm/watson/developer_cloud/language_translation/v2/model/Language.java
src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationIT.java
src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationTest.java

Allow users to use an Enum, instead of Strings (i.e. "Language.ENGLISH" instead of  "en")
This should fix #225

Language Translation - Allow users to use a "Language" Enum instead of "String".

---

src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java

Another take at resolving the JNDI class loading problem on Android. Catch any exception or error generated by `Class.forName()` call.

Check if JNDI is available before using

---

src/test/java/com/ibm/watson/developer_cloud/WatsonServiceUnitTest.java
src/test/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/ConversationTest.java
src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationTest.java
src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierTest.java
src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsTest.java
src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java
src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsTest.java
src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java
src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerTest.java
src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3_beta/ToneAnalyzerTest.java
src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionTest.java

Remove MockServer and use MockWebServer in unit tests (see #316)

Migrate unit tests to OkHttp's MockWebServer

---

.utility/travis.sh
pom.xml

#322: The Travis build seems to pass, even though the integration tests fail (see [Travis build log](https://travis-ci.org/watson-developer-cloud/java-sdk/jobs/136002119#L716))

Enforce travis.sh failure when maven fails

---

src/main/java/com/ibm/watson/developer_cloud/relationship_extraction/v1_beta/model/Dataset.java
src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java

This pull request fixes the issues developers targeting older Android versions were seeing due to the use of `javax`. This has been tested with API 19 (Android 4.4), API 21 (Android 5.0), and API 23 (Android 6.0).

Fix javax android compatability

---

src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java

Upgrading from v2.7 to v3 can make requests like `naturalLanguageClassifier.createClassifier(name, "en", trainingData)` fail silently, because `execute()` is missing. This pull request adds a `finalize` method to `ServiceCall` which outputs a warning if the call has not been executed.

Warn developer when Requests are not executed

---

src/main/java/com/ibm/watson/developer_cloud/http/ServiceCall.java
src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
src/main/java/com/ibm/watson/developer_cloud/util/ResponseConverterUtils.java
src/main/java/com/ibm/watson/developer_cloud/util/ResponseUtils.java

Following the PECS pattern (Producer extends, Consumer super), I added some generics goodness to the SDK. This enables a more flexible usage, e.g. to write generic `ServiceCallback` instances:
```java
ServiceCallback<GenericModel> cb = (GenericModel m) -> /* do something */;
service.createClassifier(name, "en", trainingData).enqueue(cb);
```

Improve ServiceCall and Response generics

---

pom.xml
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/util/ZipUtils.java
src/main/java/com/ibm/watson/developer_cloud/service/AlchemyService.java
src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzer.java
src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalytics.java
src/main/java/com/ibm/watson/developer_cloud/util/RequestUtils.java

Following the efforts to keep the method count and Android binary size low, it is now safe to remove Apache Commons Lang as dependency. This is a reduction of 3,582 methods and 435 kb :tada:  
To keep a pleasant testing experience, Apache Commons Lang is still included in the tests.

Remove Apache Commons Lang dependency

---

src/main/java/com/ibm/watson/developer_cloud/util/DateDeserializer.java
src/main/java/com/ibm/watson/developer_cloud/util/DateSerializer.java

This fix prevents multithreading bugs with `SimpleDateFormat` in `DateSerializer` and `DateDeserializer`.
> Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.
-- [SimpleDateFormat documentation](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)

Synchronize SimpleDateFormat usage

---

src/main/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/model/MessageResponse.java
src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java
src/test/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/ConversationTest.java
src/test/java/com/ibm/watson/developer_cloud/util/CredentialUtilsTest.java
src/test/resources/conversation/conversation.json

Added a new util method to CredentialUtils to allow clients to get the user name and password from the VCAP_SERVICES.
Update the conversation payload to reflect the fact that output.text in the response is now a string array and that an input.text property has also been added to the response payload.
Added helper methods to parse the input and output property values (maps)
@max-vogler ^^^

Add get username and password util, update conversation payload

---

examples/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/ResizeASolrClusterExample.java
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/ClusterLifecycleManager.java
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRank.java
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/ApiConstants.java
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/SolrClusterResizeRequest.java
src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/model/SolrClusterSizeResponse.java
src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankIT.java
src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankTest.java
src/test/resources/retrieve_and_rank/resize.json

Add a cluster resize API that allows posting a resize operation and getting information on a cluster's size using the Retrieve&Rank service.  
In addition there is an example file that shows how to use the new API. 

Add Solr resize API to R&R

---

examples/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionIndexDocumentExample.java
src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversion.java
src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/model/IndexConfiguration.java
src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/model/IndexDocumentOptions.java
src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/model/Metadata.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionIT.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java
src/test/resources/document_conversion/html-with-extra-content-input-index-dry-run.json

This submission includes new API calls for the Document Conversion Service that will allow you to access the index_document endpoint:
```java
public ServiceCall<String> indexDocument(final IndexDocumentOptions indexDocumentOptions)
```
This is a synchronous call that will allow you to convert and index a document into a SOLR collection (via the Retrieve and Rank service) in one operation.  A "dry run" of the indexing can be submitted to preview the indexed results prior to actual indexing.

[document-conversion] Adds index document API

---

src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java

AlchemyVision and Visual Recognition use `watson_vision_combined` instead of `visual_recognition` in the `VCAP_SERVICES`. This PR fixes the service name so that credentials can be extracted automatically

Fix #371 by using the name as in the VCAP_SERVICES

---

src/test/java/com/ibm/watson/developer_cloud/MultiThreadTest.java
src/test/java/com/ibm/watson/developer_cloud/WatsonServiceTest.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyDataNewsIT.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyLanguageIT.java
src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyVisionIT.java
src/test/java/com/ibm/watson/developer_cloud/concept_insights/v2/ConceptInsightsIT.java
src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationServiceIT.java
src/test/java/com/ibm/watson/developer_cloud/conversation/v1_experimental/ConversationServiceIT.java
src/test/java/com/ibm/watson/developer_cloud/dialog/v1/DialogServiceIT.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionIT.java
src/test/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversionTest.java
src/test/java/com/ibm/watson/developer_cloud/language_translation/v2/LanguageTranslationIT.java
src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierIT.java
src/test/java/com/ibm/watson/developer_cloud/personality_insights/v2/PersonalityInsightsIT.java
src/test/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRankIT.java
src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsIT.java
src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechIT.java
src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerIT.java
src/test/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/TradeoffAnalyticsIT.java
src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionIT.java
src/test/resources/config.properties
src/test/resources/logging.properties

This pull request will ignore integration tests if the `config.properties` file does’t have credentials to run them.

Ignore tests without credentials

---

core/src/main/java/com/ibm/watson/developer_cloud/util/DateDeserializer.java
src/test/java/com/ibm/watson/developer_cloud/util/DateDeserializerTest.java

The parser had no tests.  I was looking at #445 and thought I'd
add one (even though the test itself is trivial).  Also adds one
slightly more liberal date format for time parsing.

Adds test for DateDeserializer parser

---

retrieve-and-rank/src/main/java/com/ibm/watson/developer_cloud/retrieve_and_rank/v1/RetrieveAndRank.java

We currently support up to size 14 clusters and may increase that
in the future. We don't want to have to update the client code
every time we change the upper limit. Our service will respond
with appropriate error messages if the size passed in is too large.

Do not validate upper size limit when creating R&R clusters.

---

text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/AudioFormat.java

This allows the normal TextToSpeech API to be used, with PCM
AudioFormats with a rate set.
Deprecate the old PCM constant, as it can't be used safely.
This adds a sane way of using the previous fix to #454 (c78d199ac0cc333354fe753056dbd8789659de7a)

Add AudioFormat.getPCM() to set the rate

---

core/src/main/java/com/ibm/watson/developer_cloud/http/ServiceCall.java

Nice to tell developers that the implementation of ServiceCall.execute() will throw an unchecked exception (RuntimeException) that they can choose to handle or not

Throw unchecked exception in ServiceCall interface

---

core/src/main/java/com/ibm/watson/developer_cloud/util/DateDeserializer.java
tests/src/test/java/com/ibm/watson/developer_cloud/util/DateDeserializerTest.java

It appears that sometimes epoch seconds are used in dates instead of
a normal string date.  The date deserialize was modified to include
the ability to accept both epoch seconds and epoch milliseconds as
well as normal dates.
Fixes #474

Deals with a situation where epoch seconds

---

tests/src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierIT.java
tests/src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierTest.java

Add new Unit tests for NLC
refactor integration tests
I was not able to modify the . config.properties.enc file.  The classifier id it uses is no longer around.  Created a new one but need to modify that file.  So in that file can you replace it with the following
natural_language_classifier.classifier_id=e82f62x108-nlc-5806

add new tests for NLC

---

tests/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionIT.java
tests/src/test/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognitionTest.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ClassifyImagesOptions.java

Early today I asked a question about this, see here  [https://github.com/watson-developer-cloud/java-sdk/issues/481](url).
I decided to adjust the code to fit my purpose, but maybe others can benefit as well.
A simple example is based on a file, but the idea is that you do NOT have a file, only a stream:
```
byte[] fileBytes = Files.readAllBytes(Paths.get(filelocation));
options = new ClassifyImagesOptions.Builder()
.images(fileBytes,"outsideDummy.png") 
.build(); 
```

added byte array support to classify an in memory image

---

discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/document/DocumentManager.java
tests/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java

Adds the ability to add `metadata` during document create/update for Discovery service - see #510

Add metadata to Discovery document create/update

---

discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/environment/CreateEnvironmentRequest.java
tests/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java

Fixes the environment size enum serialization issue (it was outputting `FREE` instead of `0`) see the API spec -> https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Environments/post_v1_environments

Fix environment size enum serialization for Discovery

---

tests/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java

Skip the test rather than failing if no credentials are entered.
Also fix a warning in the code.

Add check for invalid credentials

---

discovery/README.md

This fixes the issue #525
```
Object name changed from 'service' to 'discovery'
Line2: Method name changed from 'setEndpoint' to 'setEndPoint'
```

[discovery] Fix the usage example in Readme

---

examples/java/com/ibm/watson/developer_cloud/speech_to_text/v1/CustomizationExample.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java

Adds the Speech to Text getCorpus() method requested in issue https://github.com/watson-developer-cloud/java-sdk/issues/498.

Add Speech to Text getCorpus() method

---

build.gradle

This restores the behaviour of the Maven build.

Generate Java 7 bytecode to be Android compatible

---

CHANGELOG.md
alchemy/build.gradle
conversation/build.gradle
core/build.gradle
dialog/build.gradle
discovery/build.gradle
document-conversion/build.gradle
language-translation/build.gradle
language-translator/build.gradle
natural-language-classifier/build.gradle
personality-insights/build.gradle
retrieve-and-rank/build.gradle
speech-to-text/build.gradle
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/RecognizeCallback.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/WebSocketManager.java
text-to-speech/build.gradle
tone-analyzer/build.gradle
tradeoff-analytics/build.gradle
visual-recognition/build.gradle

okhttp-ws is gone, see https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-350. Without an update to at least OkHttp 3.5 it's very hard to use the java-sdk with newer versions of OkHttp, especially on Android.
I've tried to keep the changes to a minimum.

Update OkHttp to v3.6.0

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/WordData.java

Add the count attribute to the Speech to Text WordData object for consistency with the service.  This PR addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/565.

:new:Add count attribute to Speech to Text WordData object

---

examples/java/com/ibm/watson/developer_cloud/speech_to_text/v1/CustomizationExample.java
examples/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationExample.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeakerLabel.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechModel.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Word.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsIT.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsTest.java

This PR addresses the following:
- Adds the Text to Speech `getWord()` method for customization (issue https://github.com/watson-developer-cloud/java-sdk/issues/527)
- Updates comments for Speech to Text session-based methods to remove references to cookies and to describe default timeout as 30 seconds instead of 15 minutes (issue https://github.com/watson-developer-cloud/java-sdk/issues/537)
- Changes "en-us" to "en-US" in Text to Speech customization examples.
- Makes a few small wording changes to parameter descriptions for Text to Speech customization methods.
**Note:** The Text to Speech integration test had an existing failure for the IPA example.  That failure is orthogonal to the other changes, so I commented the single IPA example translation from the test for now, pending …

Add Text to Speech getWord() method and clean up Speech to Text comments

---

text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/CustomTranslation.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsIT.java

Add support for the part of speech for Text to Speech `CustomTranslation` objects.  The part of speech is added by the `saveWords()` method and returned by the `getWords()` and `getWord()` methods.  The object has a constructor that accepts a `PartOfSpeech` constant.  Support is available only for Japanese; the service will soon handle errors related to invalid part of speech specifications and to use of the part of speech with languages other than Japanese.  This commit addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/538.

Add part of speech support for the Text to Speech CustomTranslation object

---

examples/java/com/ibm/watson/developer_cloud/speech_to_text/v1/CustomizationExample.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java

This PR address two issues for the Speech to Text service:
- It changes the `allowOverride` parameter of the `addTextToCustomizationCorpus()` method to `allowOverwrite`.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/574.
- It adds the `addCorpus()` method to replace the `addTextToCustomizationCorpus()` method to match the service and the Node SDK.  It deprecates the old version of the method.  It also moves the `allowOverwrite` parameter to the end of the method signature, since it's the sole optional parameter.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/573.
The Speech to Text tests and examples have been modified to use the new version of the method.  I have tested the old version of the method independently of the …

Add addCorpus() method and correct allowOverride parameter

---

language-translation/README.md
language-translator/README.md

Revised the links for the service documentation to go to the new markdown-sourced HTML pages for both the Language Translator and Language Translation service readmes.

Updating links to documentation

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Customization.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Word.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/CustomVoiceModel.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/Voice.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsIT.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsTest.java

Changed the `Word.Sort` enum definition to improve how we access the strings associated with the different constants.  Got the idea from how Tradeoff Analytics defines `Column` types.  (And I really disliked the switch statement in the `getWords()` method.)
Also improved the comments for the enums `Word.Type`, `Word.Sort`, and `Customization.WordTypeToAdd`, and tweaked the definition of the IT custom model.

Improve how Word.Sort enum is handled and general enum comments

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognitionJob.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechModel.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechResults.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/WordData.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java
speech-to-text/src/test/resources/speech_to_text/job.json
speech-to-text/src/test/resources/speech_to_text/word.json
speech-to-text/src/test/resources/speech_to_text/words.json
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/CustomVoiceModel.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsTest.java

The `WordData` object was looking for a string for the `error` field, but the field is returned as an array of string-to-string mappings.  The fix prevents the object from throwing an exception when information about a word with a faulty definition is returned.  This PR addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/564.
The PR also makes some small improvements to a few other files, none major.

Fix definition of error field for Speech to Text WordData object

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognizeOptions.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/WebSocketManager.java

Move the `customization_id` from the `start` message to a query parameter of the connection request for a WebSocket `recognize` call.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/540.

Enable customization for Speech to Test WebSocket recognition requests

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/Word.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java

Fix an issue with an existing `Word` constructor that made it difficult to add a new word without a `sounds_like` field, and expand the list of constructors to make it simpler to add new `Word` objects with different combinations of supported parameters.  This PR addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/584.

Fix and expand constructors for Speech to Text Word object

---

CHANGELOG.md
examples/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationExample.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/model/CustomVoiceModel.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsIT.java
text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/CustomizationsTest.java

Update the Text to Speech customization interface to become more parallel with the service and with the Node SDK while maintaining the object-based approach to calling methods:
- Add `createCustomVoiceModel()` and `updateCustomVoiceModel()` methods, and deprecate `saveCustomVoiceModel()` method.  The new methods also prevent updating an existing model's language, and they make it possible to provide the capability to add words on an update.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/531.
- Add `addWords()` and `addWord()` method, and deprecate `saveWords()` method.  This is purely to make the interface parallel with the service.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/598.
- Add `getCustomVoiceModel()` method …

Update Text to Speech customization interface

---

core/src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java

I got an email that seems related to #167, from someone using version 3.5.3. Checking for both javax classes should hopefully resolve this.

add check for javax.naming.InitialContext

---

language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/Language.java

Translation without modelId specified is possible only with Language enum values. But currently there only several languages declared in the enum.
I added to enum all languages from https://gateway.watsonplatform.net/language-translator/api/v2/identifiable_languages response to be able to do all possible translations.

Add all supported languages to enum

---

gradle.properties
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java

Related to #635
Reverts the encoding so TTS won't read "+" when returning a space.

[text to speech] Special Character failure resolution

---

discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/document/CreateDocumentRequest.java
discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceTest.java

Currently when the user creates a document the response returns an Id for the indexed document. We are adding a new functionality for the users that want to provide a specific document ID when creating a document. With this change the users can use their own ID, which may be from another system, to refer to a document.

[discovery] :new: Provide a specific document Id when creating a document

---

natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/DisambiguationResult.java
natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesResult.java
natural-language-understanding/src/test/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstandingIT.java

Fixes #640.  Add model for disambiguation and property in EntitiesResults

[NLU] Add disambiguation property

---

text-to-speech/src/test/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeechTest.java

The tts tests were broken when a fix was commited to change the
encoded that wasn't propogated to the tests.  I've added that change,
now they should work.

fix broken tts test

---

core/src/main/java/com/ibm/watson/developer_cloud/http/RequestBuilder.java
discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java

Use stricter URI encoding for URLs to handle vert-bar, braces, caret, backslash.

---

tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneOptions.java
tone-analyzer/src/test/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzerIT.java

Adds an `includeSentences() `method to the `ToneOptions.Builder` class that accepts a boolean to indicate the disposition of sentence-level analysis.  See issue https://github.com/watson-developer-cloud/java-sdk/issues/715.

Add ability to indicate no sentence-level analysis with tone() method

---

alchemy/src/test/java/com/ibm/watson/developer_cloud/alchemy/v1/AlchemyVisionIT.java

These alchemy vision tests have been failing for several days now and are holding up work. The failures are server-side problems and not problems with the SDK itself. This PR disables them so we can make progress until they are fixed.

Disable failing alchemy vision tests

---

.travis.yml

This PR adds the `--continue` option to the `./gradlew test` command in travis.yml so that travis will run the full test suite on a commit even when one or more tests fail.  This will make it easier to determine which commit is the root cause of a failing test.

Change travis yml to run all tests -- not stop on first failure

---

conversation/src/test/java/com/ibm/watson/developer_cloud/conversation/v1/ConversationServiceIT.java

Changed query to use a query string that matches requests issued elsewhere in the test suite.

Fix conversation testListLogsWithPaging by using a better query string

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java

I believe there is typo of setting up the query options to use a customization for the method of recognizeUsingWebSocket in SpeechToText.  According to my testing, the change worked within my app. Anyone pls review and merge it maybe? Thanks.

Fixed web socket options setting up typo with customizationId.

---

discovery/README.md

Corrects `"<collectionId"` to `"<collectionId>"`.

Correct minor typo in Discovery readme

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognizeOptions.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java

Added customization_weight parameter for speech to text. This is based on documentation here: https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#recognize_audio_websockets
Let me know if I messed anything up. Thanks!

Adding customization weight for speech to text

---

natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/DocumentSentimentResults.java
natural-language-understanding/src/test/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstandingTest.java

Matches the structure of the document field in sentiment results with the NLU documentation.
Adds a missing label field to DocumentSentimentResults class 
#814

Adds label field to NLU DocumentSentimentResult

---

personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ProfileOptions.java

As written in the API documentation, Korean is now a supported input language for the Personality Insights API: https://www.ibm.com/watson/developercloud/personality-insights/api/v3/#JavaProfileOptions

Add Korean language for Personality Insights input

---

.travis.yml
gradle.properties

The GitHub pages weren't being updated on tagged commits. This small change in the Travis YAML file should fix that.

Make sure Travis updates the GitHub pages on tagged commits

---

personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ProfileOptions.java

Before the Personality Insights service was being generated programmatically, there was a method to get the returned profile in CSV format. This was removed in the 4.0.0 release.
This PR adds that functionality back with a new `getProfileAsCSV()` method.

Add handwritten method for getting profile in CSV format

---

.bumpversion.cfg
.travis.yml
core/build.gradle
core/src/test/java/com/ibm/watson/developer_cloud/util/CredentialUtilsTest.java

Fixes #831 
This PR ensures that upon making releases, the final jar with dependencies is automatically uploaded to the appropriate GitHub release.
It also fixes the missing dependency for one of the new core unit tests, which was previously being skipped in Travis. This should now run properly.

Automatic jar upload

---

discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Enrichment.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/EnrichmentOptions.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentCategories.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentEmotion.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentEntities.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentFeatures.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentKeywords.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentRelations.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentSemanticRoles.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentSentiment.java
discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java

Fixes #826 
The Discovery service has moved to using NLU-based enrichment options. This PR makes those corresponding model changes.

Discovery patch

---

.bumpversion.cfg
.travis.yml
core/build.gradle
core/src/test/java/com/ibm/watson/developer_cloud/util/CredentialUtilsTest.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Enrichment.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentCategories.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentEmotion.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentEntities.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentFeatures.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentKeywords.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentRelations.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentSemanticRoles.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/NluEnrichmentSentiment.java
discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java
personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/model/ProfileOptions.java
personality-insights/src/test/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsightsTest.java

This PR updates Discovery to use the new NLU-based Enrichment models and fixes an issue with adding/updating configurations as described [here](https://github.com/watson-developer-cloud/java-sdk/issues/826).
It also adds back the old `getProfileAsCSV()` method to Personality Insights that had been missing since v4.0.0.

Release v4.2.0

---

discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/AddDocumentOptions.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/TestConfigurationInEnvironmentOptions.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/UpdateDocumentOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/CreateModelOptions.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/ClassifyOptions.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/CreateClassifierOptions.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/DetectFacesOptions.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/model/UpdateClassifierOptions.java

Resolves #839 
Some warnings were being thrown with the previous Javadocs because of missing descriptions on `@throws` tags. These have been added and the change was also made in the generator code.

Fix javadoc warnings about the @throws tag

---

core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java

Fixes #838 
~~This PR makes sure that if the user of a VR service changes the endpoint, the authorization is set in the header like in other services.~~
~~Unfortunately, the change is being made to the VR service file, meaning it will have to be tweaked post-codegen. This is just due to the nature of VR using an API key most of the time but a username and password for the dedicated option.~~
After new updates, `WatsonService` has been changed to store the username and password. The VR service will then check for those values to decide which authorization method to use. Presence of a username and password guarantees the use of a dedicated VR service.
The new changes to the VR service class can also be added to the generator code, eliminating the need for post-generation tweaks.

Set authorization in header for VR dedicated

---

README.md

With the last release, there was an issue getting the version number right and it caused the link to download the jar in the README to be incorrect. This PR makes that small fix to target the correct location.

Fix broken link to download jar

---

README.md
document-conversion/README.md
document-conversion/src/main/java/com/ibm/watson/developer_cloud/document_conversion/v1/DocumentConversion.java

This PR adds documentation and Javadoc changes to reflect Document Conversion's retirement in October 2017.

Deprecate doc conversion

---

core/src/test/java/com/ibm/watson/developer_cloud/service/ErrorResponseTest.java

I created this test to make sure I understood how Java formats it's exceptions, and I figured we may as well add it to the test bucket.

New test for error handling

---

language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/CreateModelOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/DeleteModelOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/GetModelOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiableLanguage.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiableLanguages.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiedLanguage.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifiedLanguages.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/IdentifyOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/ListIdentifiableLanguagesOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/ListModelsOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslateOptions.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/Translation.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationModel.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationModels.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/model/TranslationResult.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/package-info.java
language-translator/src/test/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslatorIT.java
language-translator/src/test/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslatorTest.java

This PR adds new newest generated code for Language Translator as of 2/8/18 for the purpose of the Java SDK 5.0.0 release.

Add newest generated code for Language Translator

---

natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifier.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/Classification.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/ClassifiedClass.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/Classifier.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/ClassifierList.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/ClassifyOptions.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/CreateClassifierOptions.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/DeleteClassifierOptions.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/GetClassifierOptions.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/model/ListClassifiersOptions.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/package-info.java
natural-language-classifier/src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierIT.java
natural-language-classifier/src/test/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifierTest.java
natural-language-classifier/src/test/resources/natural_language_classifier/metadata.json

This PR adds new newest generated code for Natural Language Classifier as of 2/8/18 for the purpose of the Java SDK 5.0.0 release.

Add newest generated code for Natural Language Classifier

---

README.md
conversation/README.md
discovery/README.md
natural-language-understanding/README.md
tone-analyzer/README.md
visual-recognition/README.md

This PR removes references to the old static version date strings in documentation, since these have been removed in favor of explicitly specifying the desired version date in the latest release.

Update references to old static version strings

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/websocket/SpeechToTextWebSocketListener.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java

Currently, when setting the JSON body for a `recognizeUsingWebSocket()` call, the JSON keys are left as camelCase, so some parameters are being unrecognized by the service (ex: `interimResults`).
This PR ensures that the JSON body is properly formatted.

Fix broken parameter passing when calling recognizeUsingWebSocket

---

.bumpversion.cfg
java-sdk/build.gradle

This PR adds the Assistant service as a Gradle dependency so that it's packaged in the JAR. This was accidentally left out in the last release.

fix(assistant): Add missing dependency line for Assistant

---

speech-to-text/README.md

The microphone example shows the old API.
The continues method doesn't exist anymore. And it's not necessary.
The SpeechResults class has been Renamed to SpeechRecognitionResults.
This is a small change in the readme.

Fix bug in the microphone example

---

discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Conversions.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Filter.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Histogram.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Nested.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryAggregation.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryEntitiesOptions.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryEntitiesResponseItem.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryEvidence.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryEvidenceEntity.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryNoticesResult.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryRelationsOptions.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryRelationsRelationship.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/QueryResultResultMetadata.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/SegmentSettings.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Term.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/Timeslice.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/TopHits.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/TopHitsResults.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/query/AggregationDeserializer.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/query/AggregationType.java
discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java

Fixes #854 
This PR adds support for the remaining Discovery aggregations, while also adding in a default aggregations should the service add future aggregations that aren't explicitly supported by the SDK.
Besides that change, this PR introduces some other updates to the Discovery service that came along with regenerating the code. Full details will be in the changelog for the v5.2.1 release

Add support for remaining Discovery aggregations

---

speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/AcousticModel.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/CreateJobOptions.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/GetModelOptions.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/LanguageModel.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognitionJob.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechModel.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechRecognitionResult.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SpeechRecognitionResults.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/SupportedFeatures.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextTest.java

This PR adds the latest changes in the Speech to Text service as of 4/17/18.

[Speech to Text] Add newest generated code

---

tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneChatOptions.java
tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/model/ToneOptions.java

This PR adds the latest changes in the Tone Analyzer service as of 4/17/18.

[Tone Analyzer] Add newest generated code

---

README.md
assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/Assistant.java
assistant/src/test/java/com/ibm/watson/developer_cloud/assistant/v1/AssistantServiceTest.java
conversation/src/main/java/com/ibm/watson/developer_cloud/conversation/v1/Conversation.java
core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
core/src/main/java/com/ibm/watson/developer_cloud/service/security/CredentialOptions.java
core/src/main/java/com/ibm/watson/developer_cloud/service/security/IamOptions.java
core/src/main/java/com/ibm/watson/developer_cloud/service/security/IamToken.java
core/src/main/java/com/ibm/watson/developer_cloud/service/security/IamTokenManager.java
core/src/main/java/com/ibm/watson/developer_cloud/util/CredentialUtils.java
core/src/test/java/com/ibm/watson/developer_cloud/service/IamManagerTest.java
core/src/test/java/com/ibm/watson/developer_cloud/util/CredentialUtilsTest.java
core/src/test/resources/expired_iam_token.json
core/src/test/resources/valid_iam_token.json
core/src/test/resources/vcap_services.json
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifier.java
natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java
personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzer.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java

This PR adds in support for IAM in the core of the SDK. With these changes, users have the option of authenticating with Watson services using IAM tokens, which they can manage themselves or let the new `IamTokenManager` class handle.
Shout out to @dpopp07 for leading the way for this in the Node SDK. Definitely leaned on your changes for my implementation 😉

Add IAM support

---

core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java

Before the addition of IAM, the only form of authentication in the public Visual Recognition API was through an API key. This API key was then passed as a required query parameter in all of the API endpoints.
With the addition of IAM, authentication is done through a header. However, until the service changes, it will still expect an API key query parameter.
This PR changes the `setAuthentication()` method used specifically for Visual Recognition to add a dummy API key when authenticating through IAM, the idea being that this will prevent the service from complaining while actual authentication is done in the header.
Once the service changes this requirement, this dummy value can be removed.

Add dummy API key when using IAM in Visual Recognition

---

.utility/generate-api-diff.sh
.utility/generate_apidiff_index_html.sh

Unfortunately, the addition of API diff generation is not working yet. On the latest release, these were the errors thrown in Travis:
This PR looks to address those to hopefully get things running smoothly.

Fix issues with API diff generation

---

language-translator/README.md
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v2/LanguageTranslator.java

This PR adds a deprecation notice both in the Language Translator v2 class and in the service README.

Add deprecation notice for Language Translator v2

---

core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
core/src/test/java/com/ibm/watson/developer_cloud/service/AuthenticationTest.java

This PR handles the case where the user authenticates with a username and password in the following manner:
```
username: "apikey"
password: "<iam_apikey>"
```
The SDK now recognizes this and automatically creates an IAM token manager instance to handle it.

Handle username and password authentication with "apikey"

---

.bumpversion.cfg
README.md
assistant/README.md
conversation/README.md
discovery/README.md
language-translator/README.md
natural-language-classifier/README.md
natural-language-understanding/README.md
personality-insights/README.md
speech-to-text/README.md
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
text-to-speech/README.md
tone-analyzer/README.md
visual-recognition/README.md

This PR fixes the `addCorpus()` method by fixing the way the file is sent to be handled properly by the service.
This fix will be a handwritten one for the immediate future.

Fix addCorpus()

---

core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
core/src/test/java/com/ibm/watson/developer_cloud/service/AuthenticationTest.java

This PR ensures that users authenticating with an API key on ICP do not perform the usual token exchange, instead going through basic auth.

Add support for ICP auth

---

.travis.yml

This PR fixes the deployment of Javadocs from Travis on releases. Somehow I didn't catch that we needed to change the target JDK when we switched from `oraclejdk7` to `openjdk7` in [this PR](https://github.com/watson-developer-cloud/java-sdk/pull/981).

Fix automatic deployment of javadocs

---

README.md
core/src/main/java/com/ibm/watson/developer_cloud/http/HttpClientSingleton.java
core/src/main/java/com/ibm/watson/developer_cloud/http/HttpConfigOptions.java
core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
core/src/test/java/com/ibm/watson/developer_cloud/http/HttpConfigTest.java
core/src/test/java/com/ibm/watson/developer_cloud/service/WatsonServiceTest.java

This PR gives users the ability to disable SSL verification in subsequent HTTP requests. The new way to set this also includes setting a proxy, and this is all wrapped up in a new `HttpConfigOptions` class.
Documentation has been added to the main README to explain this to users.

Add ability to disable SSL verification

---

core/src/main/java/com/ibm/watson/developer_cloud/http/RequestBuilder.java
core/src/test/java/com/ibm/watson/developer_cloud/service/RequestBuilderTest.java
core/src/test/java/com/ibm/watson/developer_cloud/service/ResponseTest.java

Add the HTTP `HEAD` method to `com.ibm.watson.developer_cloud.http.RequestBuilder`, which did not include it.
Added two new tests:
* `RequestBuilderTest#testHead()` to check we can build a head request
* `ResponseTest#testExecuteWithDetailsForHead()` to validate that the headers can be retrieved from the `Response` when using the head method.
There is a slight weirdness in the test's header assertion `assertEquals(expectedHeaders, actualHeaders)` appears not to work because the underlying `Headers` class equality fails - I believe the `MockWebServer` and the `Headers.of(...)` methods produce different whitespace in the `Headers` object. Calling `toString()` on both objects produces identical strings that do pass an `equals` assertion.

feat(Core): Add HTTP HEAD method to RequestBuilder

---

.bumpversion.cfg
README.md
assistant/README.md
conversation/README.md
core/src/main/java/com/ibm/watson/developer_cloud/http/HttpClientSingleton.java
core/src/main/java/com/ibm/watson/developer_cloud/service/WatsonService.java
discovery/README.md
language-translator/README.md
natural-language-classifier/README.md
natural-language-understanding/README.md
personality-insights/README.md
speech-to-text/README.md
text-to-speech/README.md
tone-analyzer/README.md
visual-recognition/README.md

This PR fixes a bug with the `configureClient` method of the `WatsonService` class. Originally, the internal logic wasn't immediately updating the HTTP client, so the first API call after instantiation would use default HTTP settings.
The fix makes sure to set that so that it behaves as expected on every API call.

Ensure HTTP client modification happens on the first call

---

.bumpversion.cfg
README.md
assistant/README.md
conversation/README.md
discovery/README.md
language-translator/README.md
natural-language-classifier/README.md
natural-language-understanding/README.md
personality-insights/README.md
speech-to-text/README.md
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/model/RecognizeOptions.java
speech-to-text/src/test/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToTextIT.java
text-to-speech/README.md
tone-analyzer/README.md
visual-recognition/README.md

Fixes #1004 and fixes #1005.
A ping interval was added in the `recognizeUsingWebSocket()` method to ensure that no timeouts occur. Apparently, this was causing issue #1004, according to [this issue](https://github.com/square/okhttp/issues/3113) in the OkHttp repo.

Fix Speech to Text bugs

---

core/build.gradle
core/src/main/java/com/ibm/watson/developer_cloud/http/InputStreamRequestBody.java

Fixes #1018 
As described in the issue, setting the logging level to ALL was causing issues with sending files. The underlying reason for this is that the provided `InputStream` was being accessed twice: once for logging purposes, and the other for sending to the service. On the second attempt, the stream was already closed.
This PR checks the logging level before creating the internal request body for the `InputStream` and if the user is logging everything, we copy the `InputStream` contents into a `byte[]` to be accessed multiple times. Otherwise, the behavior is the same as before.

Allow for files to be sent when logging is set to ALL

---

assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v2/model/MessageOutput.java

Fixes #1021 
This PR makes the `MessageOutput` model in the Assistant v2 service extend `DynamicModel` instead of `GenericModel` to make sure it captures other keys like `user_defined`. This may be enhanced later by adding concrete models for that key depending on whether it's a static response item or not.
With this change, other keys like `user_defined` can be accessed from the `MessageResponse` with the following lines:
```java
MessageResponse messageResponse = service.message(messageOptions).execute();
Object userDefined = messageResponse.getOutput().get("user_defined")); // can now be converted to JSON, used as Map, etc.
```

Make Assistant v2 MessageOutput dynamic to capture extra keys

---

.bumpversion.cfg
README.md
assistant/README.md
conversation/README.md
discovery/README.md
language-translator/README.md
natural-language-classifier/README.md
natural-language-understanding/README.md
personality-insights/README.md
speech-to-text/README.md
text-to-speech/README.md
tone-analyzer/README.md
visual-recognition/README.md

This PR just updates version numbers across the project to prep for a patch release that will contain fixes from these PRs: https://github.com/watson-developer-cloud/java-sdk/pull/1022, https://github.com/watson-developer-cloud/java-sdk/pull/1023

Update versions for new release

---

.bumpversion.cfg
README.md
assistant/README.md
conversation/README.md
discovery/README.md
language-translator/README.md
natural-language-classifier/README.md
natural-language-understanding/README.md
personality-insights/README.md
speech-to-text/README.md
text-to-speech/README.md
tone-analyzer/README.md
visual-recognition/README.md

This PR updates version numbers across the SDK to prepare for a patch release involving some credential logic. The changes in the release can be found [here](https://github.com/watson-developer-cloud/java-sdk/pull/1032).

Update version numbers from 6.13.0 -> 6.13.1

---

assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v1/Assistant.java
assistant/src/main/java/com/ibm/watson/developer_cloud/assistant/v2/Assistant.java
compare-comply/src/main/java/com/ibm/watson/developer_cloud/compare_comply/v1/CompareComply.java
core/src/main/java/com/ibm/watson/developer_cloud/util/RequestUtils.java
core/src/test/java/com/ibm/watson/developer_cloud/service/RequestBuilderTest.java
discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/Discovery.java
language-translator/src/main/java/com/ibm/watson/developer_cloud/language_translator/v3/LanguageTranslator.java
natural-language-classifier/src/main/java/com/ibm/watson/developer_cloud/natural_language_classifier/v1/NaturalLanguageClassifier.java
natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java
personality-insights/src/main/java/com/ibm/watson/developer_cloud/personality_insights/v3/PersonalityInsights.java
speech-to-text/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/SpeechToText.java
text-to-speech/src/main/java/com/ibm/watson/developer_cloud/text_to_speech/v1/TextToSpeech.java
tone-analyzer/src/main/java/com/ibm/watson/developer_cloud/tone_analyzer/v3/ToneAnalyzer.java
visual-recognition/src/main/java/com/ibm/watson/developer_cloud/visual_recognition/v3/VisualRecognition.java

This PR adds a header for each method call which sends analytics information about the service, version, and endpoint called. It also tweaks the format of the `User-Agent` header to match that of the other SDKs, with one small difference. Here's an example of the new `User-Agent`:
`watson-apis-java-sdk-6.13.2 Mac OS X 10.14.1 Oracle Corporation 1.8.0_144`
The Java vendor is added before the Java version (both the last values in the string), because I think this will also help guide us in terms of what vendors to support.

Add headers for analytics

---

assistant/build.gradle
common/build.gradle
common/src/main/java/com/ibm/watson/common/SdkCommon.java
common/src/main/java/com/ibm/watson/common/WatsonHttpHeaders.java
common/src/main/resources/java-sdk-version.properties
common/src/test/java/com/ibm/watson/common/SdkCommonTest.java
compare-comply/build.gradle
discovery/build.gradle
language-translator/build.gradle
natural-language-classifier/build.gradle
natural-language-understanding/build.gradle
personality-insights/build.gradle
settings.gradle
speech-to-text/build.gradle
text-to-speech/build.gradle
tone-analyzer/build.gradle
visual-recognition/build.gradle

This PR adds a new `common` project with an `SdkCommon` class to handle logic that's common to the services, but doesn't belong in the core since it's project-specific. Currently, that means it handles building the `User-Agent` and `X-IBMCloud-SDK-Analytics` values that will be added to each service request.
This PR won't contain the changes to the service methods, but for reference, the code will look something like this:
```java
public ServiceCall<QueryResponse> query(QueryOptions queryOptions) {
...
RequestBuilder builder = RequestBuilder.post(RequestBuilder.constructHttpUrl(getEndPoint(), pathSegments, pathParameters));
builder.query(VERSION, versionDate);
if (queryOptions.loggingOptOut() != null) {
builder.header("X-Watson-Logging-Opt-Out", queryOptions.loggingOptOut());
}
// Add any …
```

Add common project

---

README.md

This PR is mainly concerned with updating the main README to include information about the new reactive programming library being used and supported: [RxJava](https://github.com/ReactiveX/RxJava). Some other cleanup is also in this change.
The actual implementation is in review [here](https://github.com/IBM/java-sdk-core/pull/16).

Add information about using new async library

---

.releaserc
.travis.yml
README.md
ibm-watson/build.gradle

This PR changes/fixes some things that have come up post-7.1.0 release.
First, the JAR wasn't being included in the release assets, so I added that.
Next, the release didn't work properly in CI, apparently due to the `travis_wait` command per [this discussion](https://github.com/travis-ci/travis-ci/issues/7961). I've removed that so things should work fine next time.
Finally, I made some revisions to the README, removing the section promoting the v7 release and the temporary installation steps required by some issues that came up when we originally switched to automatic releases through Bintray.

Various post-release changes

---

speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/websocket/SpeechToTextWebSocketListener.java
speech-to-text/src/test/java/com/ibm/watson/speech_to_text/v1/SpeechToTextIT.java

With WebSocket, AudioMetrics is returned as a other response.
AudioMetrics was ignored because neither "results" nor "speaker_labels" were included.

Fix AudioMetrics bug (Speech To Text)

---

.travis.yml
assistant/build.gradle
common/build.gradle
compare-comply/build.gradle
discovery/build.gradle
language-translator/build.gradle
natural-language-classifier/build.gradle
natural-language-understanding/build.gradle
personality-insights/build.gradle
speech-to-text/build.gradle
text-to-speech/build.gradle
tone-analyzer/build.gradle
visual-recognition/build.gradle

Related to https://github.com/watson-developer-cloud/java-sdk/issues/1071
This PR updates the core dependency to allow for setting up authentication when configuring a proxy. This means setting a `proxyAuthenticator` value on the `HttpConfigOptions` builder.
Additionally, a wait has been added on the deployment step in Travis since the uploading and syncing takes a while and has timed out in the past.
Thanks again @marloncarvalho for the feature!

Update core dependency to allow for proxy authentication

---

compare-comply/src/main/java/com/ibm/watson/compare_comply/v1/model/KeyValuePair.java
compare-comply/src/test/java/com/ibm/watson/compare_comply/v1/CompareComplyTest.java
compare-comply/src/test/resources/compare_comply/classify-return.json
compare-comply/src/test/resources/compare_comply/table-return.json

This PR fixes the model definition for `KeyValuePair` in the Compare and Comply service to match the API specification [here](https://cloud.ibm.com/docs/services/compare-comply?topic=compare-comply-understanding_tables#table-schema-arrangement). The previous definition was resulting in serialization errors.

Fix KeyValuePair model definition

---

visual-recognition/src/main/java/com/ibm/watson/visual_recognition/v3/VisualRecognition.java
visual-recognition/src/test/java/com/ibm/watson/visual_recognition/v3/VisualRecognitionIT.java

This PR adds a fix for the `createClassifier()` method in Visual Recognition.
It seems that when submitting files to this method, the service expects file extensions as part of the filenames. Otherwise, it doesn't accept them properly. The way the code was written previously, users had no control over the filenames for positive examples and they wouldn't include the extension.
This change adds a `.zip` to the end of the positive example filenames, which should be fine since it's the only file type the method accepts. Additionally, if users supply a filename for the negative examples that doesn't include the extension, we add it for convenience.
These are both handwritten changes post-generation and will be documented accordingly.

Fix for createClassifier

---

README.md

As the title suggests, this PR updates the main README to give instructions on how to get the global transaction ID from SDK responses.

Add documentation around getting the global transaction ID

---

discovery/src/main/java/com/ibm/watson/discovery/v1/model/EnvironmentDocuments.java

The Discovery service returns 'available' as the total number of documents for an environment.
This was previously using 'indexed' which is not what the service returns.

fix(Discovery v1): environment document count should use 'available'

---

speech-to-text/src/main/java/com/ibm/watson/speech_to_text/v1/model/RecognizeOptions.java

The `RecognizeOptions` constructor doesn't really apply the `interimResults`, so the client app can't receive non-final results as stated in the document.
This patch adds the missing `interimResults` assignment (and also the missing `processingMetrics` and `processingMetricsInterval`) back to the constructor.

Fix missing option assignments

---

compare-comply/src/main/java/com/ibm/watson/compare_comply/v1/CompareComply.java
discovery/src/test/java/com/ibm/watson/discovery/v1/DiscoveryServiceIT.java
natural-language-classifier/src/test/resources/natural_language_classifier/classification.json
natural-language-classifier/src/test/resources/natural_language_classifier/classification_collection.json
natural-language-classifier/src/test/resources/natural_language_classifier/classifier.json
natural-language-classifier/src/test/resources/natural_language_classifier/classifiers.json
speech-to-text/README.md
speech-to-text/src/test/resources/speech_to_text/jobs.json

watsonplatform.net urls will cease to function 12 feb 2021. This pull request updates the urls with corresponding onecloud urls.

Update gateway urls

---

pom.xml

Updating the version of the core to `9.12.1` so we can allow users to use username and apikey auth for cpd

fix(pom.xml): update java-sdk-core version

---

.github/workflows/deploy.yml

I removed the tag build check which did not seem to work for GHA  and put in what we do for dotnet.
1) Do a semantic release in dry run and see if it will generate a release
2) If release is true do a real semantic release and release to maven
3) if release is false print message release is skipped

ci: 9662 addcheck

---

.github/workflows/deploy.yml

semantic-release failed since the requirement for it is now node 14. This PR upgrades the node version to fix this issue.

fix(deploy.yml): up the version for node to fix semantic-release
